# 

# === C'EST LA PARTIE CENTRALE DU DOCUMENT, CE SONT LES CHAPITRES/SECTIONS .md ===
# === THIS IS THE CENTRAL PART OF THE DOCUMENT, THESE ARE THE CHAPTERS/SECTIONS .md ===
publicFolder: "creation_sitee"
lang: "fr"

# === C'EST ICI QU'ON TRAVAILLE L'APPARENCE VISUELLE ET LA MISE EN PAGE (CSS)  ===
# === THIS IS WHERE WE WORK ON VISUAL APPEARANCE AND LAYOUT (CSS) ===
theme: "creation_sitee"

# === DOCUMENT INFORMATION ===
title: "les territoires de la création située"
subtitle: ""

# === AUTHORS (MULTIPLE): "name firstname, name firstname" ===
author: "Aurélien Ramos, Camille de Singly. Sous la direction d'Hélène Soulier"
year: "2025-2026"

# === A PERSONNALISER / CUSTOMIZABLE ===
meta_1: ""
meta_2: ""
meta_3: ""
meta_4: ""

# === BOOK PAGE DIMENSIONS (mm) ===
width: 200
height: 260

# === GENERAL MARGINS (mm) ===
margin_top: 15
margin_right: 15
margin_bottom: 25.8
margin_left: 76.7

# === LEFT PAGE MARGINS (mm) ===
page_left_margin_top: 15
page_left_margin_right: 76.7
page_left_margin_bottom: 25.8
page_left_margin_left: 15


# === RIGHT PAGE MARGINS (mm) ===
page_right_margin_top: 15
page_right_margin_right: 15
page_right_margin_bottom: 25.8
page_right_margin_left: 76.7

# === GENERAL MARGINS (mm) ===
# margin_top: 20
# margin_right: 15
# margin_bottom: 25
# margin_left: 76.7

# === LEFT PAGE MARGINS (mm) ===
# page_left_margin_top: 20
# page_left_margin_right: 76.7
# page_left_margin_bottom: 25
# page_left_margin_left: 15

# === RIGHT PAGE MARGINS (mm) ===
# page_right_margin_top: 20
# page_right_margin_right: 15
# page_right_margin_bottom: 25
# page_right_margin_left: 76.7


# === LAYOUT OPTIONS ===
bleed: true
marks: true

# === CESURES OPTIONS ===
cesures_footnotes: "false"
cesures_paragraphe: "true"

# === NOTES OPTIONS ===
print_notes: "bottom"



